version: "3.5"

services:
    homepage-nginx:
        image: nginx:1.15-alpine
        container_name: homepage-nginx
        restart: always
        working_dir: /var/www/homepage
        labels:
            - traefik.enable=true
            - traefik.backend=${DOMAIN}
            - traefik.frontend.rule=Host:${DOMAIN}
            - traefik.frontend.passHostHeader=true
            - traefik.frontend.entryPoints=${TRAEFIK_ENTRYPOINTS}
            - traefik.frontend.headers.SSLRedirect=${TRAEFIK_SSLREDIRECT}
        volumes:
            - ./../:/var/www/homepage
            - ./resources/nginx/:/etc/nginx/conf.d/
            - ./logs/:/var/log/nginx/
        depends_on:
            - homepage-php

    homepage-php:
        build: build/php
        container_name: homepage-php
        restart: always
        user: ${USER_ID}
        working_dir: /var/www/homepage
        volumes:
            - ./../:/var/www/homepage

networks:
    default:
        external:
            name: webproxy